title: GMD 꿱포럼
description: Geometry Dash 꿱 포럼에 오신것을 환영합니다!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  데몬리스트 보러가기: https://github.com/just-the-docs/just-the-docs-template
